<!-- Copyright © 2026 Neil Colvin. MIT with Commons Clause; see LICENSE. -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>14</LangVersion><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable><GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1591;CS4014</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TeslaPowerwallLibrary" Version="2.1.0" />
    <InternalsVisibleTo Include="TeslaPowerwallCrestronDriver.LocalSetup.Tests" />
    <None Update="README.md" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../LICENSE" Link="LICENSE" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
