<!-- Copyright (c) 2026 Neil Colvin. MIT with Commons Clause; see LICENSE. -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework><LangVersion>14</LangVersion><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings>
    <IsTestProject>true</IsTestProject><IsPackable>false</IsPackable><GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1591;CS4014</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="5.0.0" PrivateAssets="all" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" PrivateAssets="all" />
    <PackageReference Include="CrestronHomeNUnit.TestAdapter" Version="2.3.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
